#!/usr/bin/python3
# --- Imports ---
import os
from os import listdir
from os.path import isfile, join, getsize
from sys import argv


# --- Globals ---
path = "."
show_size = False
files = []
dirs = []
MAX_NAME_LENGTH = 40
show_hidden = False

# --- Functions ---
def get_dir_size(path=os.getcwd()):
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(path):
        dirsize = 0
        for f in filenames:
            fp = os.path.join(dirpath, f)
            size = os.path.getsize(fp)
            dirsize += size
            total_size += size
    return total_size


def listElement(file, isdir):
    mlen = MAX_NAME_LENGTH
    raw_filename = file
    hidden_text = ""
    if file[0] == ".":
        if show_hidden:
            hidden_text = "  (Hidden)"
        else:
            return
    route = path + "/" + file
    padding = ""
    if len(file) > mlen:
        file = file[0:mlen-1] + "~"
    size = ""
    if show_size:
        try:
            if isdir:
                size = get_dir_size(route)
            else:
                size = getsize(path)
            if size < 1024:
                size = str(size) + " B"
            elif size < 1024**2:
                size = ("%.2f" % (size/(1024))) + " KB"
            elif size < 1024**3:
                size = ("%.2f" % (size/(1024**2))) + " MB"
            elif size < 1024**4:
                size = ("%.2f" % (size/(1024**3))) + " GB"
        except:
            size = "Unknown size"
    type = "   "
    if isdir:
        type = "DIR"
    elif os.access(route, os.X_OK):
        type = "EXE"
    elif "." in raw_filename:
        type = raw_filename.split(".")[-1].upper()
        while len(type) < 3:
            type += " "
    link = "    "
    if os.path.islink(route):
        link = "*   "
    if len(file) < mlen:
        padding = ("-" * (mlen - len(file)))
    print(" " + file + "  " + padding + "  " + type + link + size + hidden_text)


# --- Procedure ---
if len(argv) > 1:
    for arg in argv[1:]:
        if arg == "-s":
            show_size = True
        elif arg == "-h":
            show_hidden = True
        elif arg == "--help":
            print(f"Showing size by default: {show_size}.")
            print(f"Use -s to show file sizes.")
            print(f"Use -a to show hidden files.")
        else:
            path = arg
try:
    files = [f for f in listdir(path) if isfile(join(path, f))]
    dirs = [f for f in listdir(path) if not isfile(join(path, f))]
    files.sort()
    dirs.sort()
except:
    print("\nCannot list directory " + path + "\n")
    quit()

print("\n Directory of " + os.getcwd() + "\n")

if dirs:
    print (" -=- [ Directories ] -=-")
    for dir in dirs:
        listElement(dir, True)

if dirs and files:
    print("")

if files:
    print (" -=- [ Files ] -=-")
    for file in files:
        listElement(file, False)

print("")
